### ISSUE TITLE
Allow configuration of default routes for `resource`/`resources`

### ISSUE THREAD

**Issue by Emily** [lotus/router#41]
While I think the current set of routes generated by `resources` is a reasonable default, the inability to customize, or reuse chunks of routes is somewhat cumbersome when an app deviates from that particular set of routes. 

For instance, http://jsonapi.org/ requires supporting PUT for updates, and allows APIs to optionally support PATCH (with a very specific format). When building an API that conforms to that specification (and the same goes for many other specs), it is a pain to have to be specifying things like:

```ruby
resources 'widgets' do
  member do
    put '', to: 'widgets#update'
  end
end
```

It is also very visually noisy. It'd be nice if either the set of routes that `resources` creates were configurable, or if it were possible to simply configure extra methods that behaved similarly to `resources` that define a different set of routes, e.g.

```ruby
json_api_resources 'widgets'
```

Or perhaps something that behaves a bit like Rails's routing concerns, e.g.

```ruby
resources :widgets do
  concerns :json_api_resource # adds in the handful of extra routes
end
```

My favorite is probably allowing `resources` to be configured, or the `resources` like method approach. I'd be happy to put together a PR for one of them, especially if it can be slipped in before support for < ruby 2.2 is dropped (as I'm likely stuck using 2.1 for several months).

**Comment by jodosha** [comment]
@Emily Thanks for opening this discussion.
We're keen to make the set of routes more flexible. I don't like concerns or special `json_api_resources`.

> My favorite is probably allowing resources to be configured, or the resources like method approach. 

This sounds good, but I'm afraid I haven't got what you mean in terms of code. Can you please expand this concept?

> I'd be happy to put together a PR for one of them

That would be really appreciated :+1: 

> as I'm likely stuck using 2.1 for several months

Which are your stopping points? Which Lotus components are you using?

Thank you very much.

**Comment by Emily** [comment]
So by allowing resources to be configured, I really mean configuring Lotus::Router (whether at the class level or instance level) to change the set of routes that `resources` generates.

So code wise:

```ruby
Lotus::Router.configure do
  resources do |name|
    get "/#{name}", to: :whatever, name: :index
    get "/#{name}/:id", to: :whatever, name: :show
    get "/#{name}/new", to: :whatever, name: :new
    post "/#{name}", to: :whatever, name: :create
    get "/#{name}/:id/edit", to: :whatever, name: :edit
    patch "/#{name}/:id", to: :whatever, name: :update
    delete "/#{name}/:id", to: :whatever, name: :destroy
  end
end
```

That's what Lotus' current defaults would look like.

And so a modified one might look like:

```ruby
Lotus::Router.configure do
  resources do |name|
    get "/#{name}", to: :whatever, name: :index
    get "/#{name}/new", to: :whatever, name: :new
    post "/#{name}", to: :whatever, name: :create
    get "/#{name}/:id/edit", to: :whatever, name: :edit
    delete "/#{name}/:id", to: :whatever, name: :destroy
    get "/#{name}/some/custom/thing", to: :whatever, name: :something_custom
  end
end
```

`name:` is a bad key name (I couldn't think of a better one yet), but the idea is that it would allow you to still use `except: [:update]` or something, on a custom set of routes. Which would allow `resources :blah, except: [:something_custom]` or `resources :blah, only: [:something_custom, :index]` to work.

I think this could be taken further and potentially allow for multiple custom definitions:

```ruby
Lotus::Router.configure do
  resource_helper :resources do |name|
    get "/#{name}", to: :whatever, name: :index
    get "/#{name}/:id", to: :whatever, name: :show
    get "/#{name}/new", to: :whatever, name: :new
    post "/#{name}", to: :whatever, name: :create
    get "/#{name}/:id/edit", to: :whatever, name: :edit
    patch "/#{name}/:id", to: :whatever, name: :update
    delete "/#{name}/:id", to: :whatever, name: :destroy
  end

  resource_helper :api_resources do |name|
    get "/#{name}", to: :whatever, name: :index
    get "/#{name}/count", to: :whatever, name: :count
    get "/#{name}/:id", to: :whatever, name: :show
    post "/#{name}", to: :whatever, name: :create
    patch "/#{name}/:id", to: :whatever, name: :update
    delete "/#{name}/:id", to: :whatever, name: :destroy
  end
end
```

I'm not sure it's necessary, but it might be nice for applications which have both endpoints intended for direct human consumption (html, etc...) and APIs intended for machine consumption. So you could have the default `resources :foo` as well as a custom `api_resources :bar`. Maybe the API doesn't have the new/edit routes and has some extra `count` endpoint for some reason.

The custom helper definition may also be nice because it would discourage people from redefining the default `resource`/`resources` helpers, which would help to avoid confusion.

### Ruby Version

As for the Ruby 2.2 comment...

I mean to say that I'm stuck using < 2.2 for the time being not because of Lotus, but for other reasons. I noticed a number of pull requests that are adding ruby >= 2.2 as a requirement in the Gemfile. Ideally (for me anyway) any PR I put together for this would get into a release (or be back ported to an older version) before that Ruby 2.2 requirement is merged in, so that I can actually use the set of changes without having to jump through any hoops.

**Comment by jodosha** [comment]
@Emily Thanks for the great reply.

### Class vs instance configuration

Lotus::Router is the one of the few Lotus framework that don't need class level configurations. I would keep it as it is, so those configurations should be moved at the instance level.

The reason is simple. When class level configurations are involved, multiple instances of a framework can't live together in the same Ruby process without the _"framework duplication"_ technique. This is something that we apply to Controller, View and Model.

If we change how Lotus::Router works, we should change a lot of other foundations that Lotus is relying on. I'm very conservative on this aspect.

### Some ideas

What if we do:

```ruby
router = Lotus::Router.new do
  configure do
    resources do
       # ...
    end

    resource do
       # ...
    end
  end
end
```

Those two blocks can express RESTful resources as you have expressed.
The `:name` option can be called `:verb` :)

The internals of the framework aren't that much flexibile to support this feature without changing them a lot. I understand that you want to get your job done. So let me suggest a few of quick ideas to get you up and running again.

  * Would be enough to support both `PUT` and `PATCH` for update operations to get compliant to jsonapi.org ?
  * Have you considered to subclass `Lotus::Router` and to override `#resources` to get your wanted behavior?

### One configuration per router instance

> I'm not sure it's necessary, but it might be nice for applications which have both endpoints intended for direct human consumption (html, etc...) and APIs intended for machine consumption.

:-1: 

The way that Lotus wants to guide developers is to have multiple applications in the same Ruby process, one for each area. If you use Lotus full stack (`lotusrb` gem), you can have `apps/web`, `apps/api` etc..

This architecture helps to keep things simple, decoupled, faster and easy to extract.

### Ruby version

I'm glad it doesn't depend on Lotus. But technically, which gems or other kind of problems prevent you to do the upgrade? Can you please share them on this thread? https://discuss.lotusrb.org/t/supported-ruby-vms/28/10

Thank you very much!

**Comment by jodosha** [comment]
@Emily Any news on this?

**Comment by jodosha** [comment]
@Emily Closing this, feel free to reopen in case you want to resume the discussion. Thank you.
