### ISSUE TITLE
Routing gotcha - order of mounting

### ISSUE THREAD

**Issue by TigerWolf** [lotus/router#43]
First time lotus user, hope this is in the right place.

First thing that tripped me up was in `environment.rb` - if you set it up like:

```
Lotus::Container.configure do
  mount Web::Application, at: '/'
  mount Api::Application, at: '/api/'
end
```

The `/api` will never get exposed. If you change it to: 

```
Lotus::Container.configure do
  mount Api::Application, at: '/api/'
  mount Web::Application, at: '/'
end
```

Then it works as expected. 

Without looking into the internals of lotus, I'm guessing that in the first example `Web::Application` is taking over all routing.

**Comment by TigerWolf** [comment]
Please see the following failing test:

https://github.com/TigerWolf/lotus/compare/tests/multiple_router_order?expand=1

Would be happy to move close this issue and re-create on https://github.com/lotus/lotus if it is preferred.

**Comment by jodosha** [comment]
@TigerWolf yes, that is a well known issue.

The reason is that internally it uses `/api*` and `/*` namespaces. If you use `/*` before, it shadows the others because it acts as a "_too greedy catch all_".

We already have a solution in mind, but it takes time to implement. https://trello.com/c/LbpVBQuL/23-flatten-routes

Closing this for now, sorry for the poor experience.

**Comment by TigerWolf** [comment]
Good to know it's a known issue. Thanks for looking into this quickly.
