### ISSUE TITLE
Customize JSON parsing errors

### ISSUE THREAD

**Issue by Erol** [lotus/router#46]
I've been using Lotus::Router (with Lotus::Controller) in building an API, and I find the ability to specify JSON parsing via `Lotus::Router.new parsers: [:json]` very convenient. However, the router responds with a very verbose message and stacktrace when a parsing error is encountered:

```
HTTP/1.1 500 Internal Server Error
Content-Length: 2372
Content-Type: text/plain

JSON::ParserError: 757: unexpected token at '{
  "fruit": "Apple"
  "vegetable": "Cabbage"
}
'
	/Users/Erol/.gem/ruby/2.2.0/gems/json-1.8.2/lib/json/common.rb:155:in `parse'
	/Users/Erol/.gem/ruby/2.2.0/gems/json-1.8.2/lib/json/common.rb:155:in `parse'
	/Users/Erol/.gem/ruby/2.2.0/gems/lotus-router-0.2.1/lib/lotus/routing/parsing/json_parser.rb:12:in `parse'
	/Users/Erol/.gem/ruby/2.2.0/gems/lotus-router-0.2.1/lib/lotus/routing/parsers.rb:52:in `block in _redefine_call'
	/Users/Erol/.gem/ruby/2.2.0/gems/lotus-router-0.2.1/lib/lotus/routing/http_router.rb:112:in `raw_call'
	/Users/Erol/.gem/ruby/2.2.0/gems/http_router-0.11.1/lib/http_router.rb:142:in `call'
	/Users/Erol/.gem/ruby/2.2.0/gems/lotus-router-0.2.1/lib/lotus/router.rb:879:in `call'
	/Users/Erol/.gem/ruby/2.2.0/gems/rack-1.6.0/lib/rack/session/abstract/id.rb:225:in `context'
	/Users/Erol/.gem/ruby/2.2.0/gems/rack-1.6.0/lib/rack/session/abstract/id.rb:220:in `call'
	/Users/Erol/.gem/ruby/2.2.0/gems/rack-1.6.0/lib/rack/lint.rb:49:in `_call'
	/Users/Erol/.gem/ruby/2.2.0/gems/rack-1.6.0/lib/rack/lint.rb:37:in `call'
	/Users/Erol/.gem/ruby/2.2.0/gems/rack-1.6.0/lib/rack/showexceptions.rb:24:in `call'
	/Users/Erol/.gem/ruby/2.2.0/gems/puma-2.11.0/lib/puma/rack_patch.rb:13:in `call'
	/Users/Erol/.gem/ruby/2.2.0/gems/shotgun-0.9.1/lib/shotgun/loader.rb:86:in `proceed_as_child'
	/Users/Erol/.gem/ruby/2.2.0/gems/shotgun-0.9.1/lib/shotgun/loader.rb:31:in `call!'
	/Users/Erol/.gem/ruby/2.2.0/gems/shotgun-0.9.1/lib/shotgun/loader.rb:18:in `call'
	/Users/Erol/.gem/ruby/2.2.0/gems/shotgun-0.9.1/lib/shotgun/favicon.rb:12:in `call'
	/Users/Erol/.gem/ruby/2.2.0/gems/rack-1.6.0/lib/rack/urlmap.rb:66:in `block in call'
	/Users/Erol/.gem/ruby/2.2.0/gems/rack-1.6.0/lib/rack/urlmap.rb:50:in `each'
	/Users/Erol/.gem/ruby/2.2.0/gems/rack-1.6.0/lib/rack/urlmap.rb:50:in `call'
	/Users/Erol/.gem/ruby/2.2.0/gems/rack-1.6.0/lib/rack/builder.rb:153:in `call'
	/Users/Erol/.gem/ruby/2.2.0/gems/puma-2.11.0/lib/puma/server.rb:507:in `handle_request'
	/Users/Erol/.gem/ruby/2.2.0/gems/puma-2.11.0/lib/puma/server.rb:375:in `process_client'
	/Users/Erol/.gem/ruby/2.2.0/gems/puma-2.11.0/lib/puma/server.rb:262:in `block in run'
	/Users/Erol/.gem/ruby/2.2.0/gems/puma-2.11.0/lib/puma/thread_pool.rb:104:in `call'
	/Users/Erol/.gem/ruby/2.2.0/gems/puma-2.11.0/lib/puma/thread_pool.rb:104:in `block in spawn_thread'
```

Is there a way to silence or customize the error response when running on production? I'm willing to submit a PR if there is no facility yet to do this and if you feel this is a worthy feature. :)

**Comment by jodosha** [comment]
@Erol Thanks for reporting this problem. I'd love to leave Router as it is: a Rack middleware which isn't aware of error handling. The reason is that, for full stack Lotus apps, `lotusrb` handle errors, while other custom scenario like yours may use ad-hoc Rack middleware and/or solutions.

### Ready solution

`rack-errors` (if still maintained) is a good candidate.

### Custom Rack middleware

```ruby
class ExceptionHandler
  def initialize(app)
    @app = app
  end

  def call(env)
    @app.call(env)
  rescue => e
     # handle exception
  end
end
```

```ruby
# config.ru
use ExceptionHandler
run Lotus::Router.new {
  get '/books'
}
```

### Wrap inside an application

```ruby
class ApiApp
  def initialize
    @router = Lotus::Router.new do
      # ...
    end
  end

  def call(env)
    @router.call(env)
  rescue => e
    # handle exception
  end
end
```

```ruby
# config.ru
run ApiApp.new
```

**Comment by Erol** [comment]
Oh yeah, I haven't considered writing/using a middleware to handle exceptions. I'll go with that approach. Thanks!

**Comment by thhermansen** [comment]
Hi @jodosha. First of all. Thanks for working on Lotus! We begun using it at work for a few months now and it has been a joy so far.

I have a question related to this issue:

Your suggestion of rescuing `JSON::ParseError`, either in a middleware or in the Lotus application seemed ok at first though. Whenever a `JSON::ParseError` was raised we could rescue it and halt the request with a `400 Bad Request`.

Then I begun thinking; what happens if some poorly written application code, or some poorly written gem, leaks a `JSON::ParseError` (after body parsing completed successfully)? Then it would be returned as a `400 Bad Request` to the client, when it in fact should be something else.

So maybe it justifies raising a specific body parse error, or is there any other way I haven't though of yet which will ensure that no `400 Bad Request` is returned to the client unjustified.

(In a perfect world, all parse errors should be handled within the application/gem, but I'm guessing that is hard to guarantee to always be true)

**Comment by jodosha** [comment]
@thhermansen Hey, my suggestion was related to standalone usage of `lotus-router`, which doesn't support for rescuing exceptions and translate them into HTTP status codes. This is a feature of `lotus-controller` and, so of `lotusrb`.

For this use case (standalone usage), you have to manually catch the exception and return the appropriate code.

> Then I begun thinking; what happens if some poorly written application code, or some poorly written gem, leaks a `JSON::ParseError` (after body parsing completed successfully)?

I see what you mean. The problem is that, if we raise a `Lotus::Router::ParamsParseError` for our `JsonParser`, then we should force the same protocol to custom parsers who should take care of it. For instance a "home made" `XmlParser` should take care of raise `Lotus::Router::ParamsParseError` in case the XML parsing would fail.

So, I'm not keen to add defensive code for an eventual bug into other gems. Does it makes sense?

**Comment by thhermansen** [comment]
Thanks for your answer. I'm not 100% sure if I'm totally convinced. We did solve in in our application locally by raising an specific parse-error, thus getting the behaviour we wanted.

**Comment by jodosha** [comment]
@thhermansen Code or din't happen :wink: 

Do you have a concrete code example to share with the rest of us. Thank you very much. :smile:

**Comment by thhermansen** [comment]
A simple and very JSON specific implementation can be seen [here](https://github.com/gramo-org/echo_common/blob/master/lib/echo_common/lotus/routing/parsing/json_parser.rb). The BodyParseError can be handled in a middleware. I guess if something like this was to be pulled in to the framework the error the parser raised had to be well defined and as you wrote, every well written body parser should confirm to raise such an error.

**Comment by jodosha** [comment]
@thhermansen Thank you, do you also have a stacktrace of the exception (without the `rescue` clause)? Thank you!

**Comment by thhermansen** [comment]
Sure, here you go:

```
     JSON::ParserError:
       776: unexpected token at '{ bad json!'
     # ./.bundle/gems/ruby/2.2.0/gems/lotus-router-0.4.3/lib/lotus/routing/parsing/json_parser.rb:12:in `parse'
     # ./.bundle/gems/ruby/2.2.0/gems/lotus-router-0.4.3/lib/lotus/routing/parsers.rb:52:in `block in _redefine_call'
     # ./.bundle/gems/ruby/2.2.0/gems/lotus-router-0.4.3/lib/lotus/routing/http_router.rb:123:in `raw_call'
     # ./.bundle/gems/ruby/2.2.0/gems/http_router-0.11.2/lib/http_router.rb:142:in `call'
     # ./.bundle/gems/ruby/2.2.0/gems/lotus-router-0.4.3/lib/lotus/router.rb:878:in `call'
     # ./.bundle/gems/ruby/2.2.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
     # ./.bundle/gems/ruby/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:153:in `call'
     # ./.bundle/gems/ruby/2.2.0/gems/lotusrb-0.5.0/lib/lotus/middleware.rb:52:in `call'
     # ./.bundle/gems/ruby/2.2.0/gems/lotusrb-0.5.0/lib/lotus/application.rb:217:in `call'
     # ./apps/api/application.rb:62:in `call'
     # ./.bundle/gems/ruby/2.2.0/gems/http_router-0.11.2/lib/http_router.rb:193:in `process_destination_path'
     # (eval):18:in `call'
     # ./.bundle/gems/ruby/2.2.0/gems/http_router-0.11.2/lib/http_router.rb:288:in `raw_call'
     # ./.bundle/gems/ruby/2.2.0/gems/lotus-router-0.4.3/lib/lotus/routing/http_router.rb:123:in `raw_call'
     # ./.bundle/gems/ruby/2.2.0/gems/http_router-0.11.2/lib/http_router.rb:142:in `call'
     # ./.bundle/gems/ruby/2.2.0/gems/lotus-router-0.4.3/lib/lotus/router.rb:878:in `call'
     # ./.bundle/gems/ruby/2.2.0/gems/lotusrb-0.5.0/lib/lotus/container.rb:36:in `call'
     # ./.bundle/gems/ruby/2.2.0/gems/rack-test-0.6.3/lib/rack/mock_session.rb:30:in `request'
     # ./.bundle/gems/ruby/2.2.0/gems/rack-test-0.6.3/lib/rack/test.rb:244:in `process_request'
     # ./.bundle/gems/ruby/2.2.0/gems/rack-test-0.6.3/lib/rack/test.rb:67:in `post'
     # ./spec/api/requests/invalid_json_spec.rb:8:in `block (2 levels) in <top (required)>'
```
