### ISSUE TITLE
Non-Standard Port Missing When `router.url` Called

### ISSUE THREAD

**Issue by bfad** [lotus/router#49]
When calling `router.url` when running on a non-standard port, the port number is not included in the URL.

Example Code
```ruby
require 'lotus/router'

app = Lotus::Router.new do
  get '/', to: ->(env) { [200, {}, [app.url(:home)]] }, as: :home
end

Rack::Server.start app: app, Port: 2300
```

If you then visit `http://localhost:2300/` it returns `http://localhost/`

It would be nice if Lotus router checked the port against the protocol and included the port in the URL if it was not the standard for the protocol.

**Comment by AlfonsoUceda** [comment]
@bfad router accepts options parameter:
```ruby
require 'lotus/router'

app = Lotus::Router.new port: 2300 do
  get '/', to: ->(env) { [200, {}, [app.url(:home)]] }, as: :home
end

app.url(:home)
```

**Comment by bfad** [comment]
How would you pass in the port that was passed to rackup? (I'd rather not hard-code something that actually will change based on how the server is started from the command-line)

Also, this looks like a nice work-around, but what would be the reason for router.url not detecting non-standard ports and adding them to the URL since it's necessary?

**Comment by jodosha** [comment]
@bfad `Lotus::Router` is an object that expects that value in the constructor. As @AlfonsoUceda mentioned, if you pass it, it works as expected. The reason to not auto detect Rack env is simplicity and less magic.

I guess you're using `rackup`, but that means for us to reproduce their CLI arg parsing here. It has a cost of maintenance and it may not solve this problem (eg. if you use `puma` CLI), they may have a different set of args.

It's difficult to understand which port your application is running on if we don't own the context. For instance, in `lotusrb` we have `lotus server`. In this case we control the CLI and we can pass down the options to the router.

Lotus is designed in this way: when you use `lotusrb` everything is orchestrated for you, but when you use standalone frameworks it's up to you to pass the expected options.

To solve your issue, because you are in control of the CLI, you can scan `ARGV` and check if a custom port is used and pass both to `Lotus::Router` and `Rack::Server.start`.

**Comment by bfad** [comment]
Thanks for filling me in on the philosophy here. My thought processes was not that the command-line arguments needed to be parsed but that the rack environment variables could be parsed to get the HTTP_PORT. I guess that's still a bit of behind-the-scenes magic that may not work in all contexts. Thanks again.
